name: lua
description: A library and cli for running, disassembling, and debugging Lua programs.
version: 0.0.1
homepage: https://github.com/P-T-/luadart
author: Andre Lipke <andre.lipke@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  tuple: "^1.0.1"
  args: "^1.4.1"

dev_dependencies:
  test: ^0.12.0
